package org.micromanager.rapp.utils;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.net.URL;

public class ImageViewer extends JInternalFrame {
    private URL default_path = this.getClass().getResource("");
    private String path = default_path.toString().substring(6);
    /**
     * Creates new form Images_From_Folder_Navigation
     */
    public ImageViewer() {
        initComponents();
        // display first image
        showImage(pos);
    }

    // the index of the images
    int pos = 0;

    // get images list
    public String[] getImages()
    {
        File file = new File(path.concat("Resources/Images/"));

        String[] imagesList = file.list();
        return imagesList;
    }

    // display the image by index
    public void showImage(int index)
    {
        String[] imagesList = getImages();
        String imageName = imagesList[index];
        System.out.println("Image : "+imageName);
        ImageIcon icon = new ImageIcon(path.concat(imageName));
        Image image = icon.getImage().getScaledInstance(400, 400, Image.SCALE_SMOOTH);
        jLabel_Image.setIcon(new ImageIcon(image));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        Box button_box  = Box.createHorizontalBox();
        jLabel_Image = new JLabel();
        JButton jButton1 = new JButton();
        JButton jButton_Next = new JButton();
        JButton jButton_Previous = new JButton();
        JButton jButton_Last = new JButton();

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ImageIcon icon = new ImageIcon(path.concat("Resources/Images/first.jpg"));
        Image img = icon.getImage() ;
        Image newimg = img.getScaledInstance( 30, 20,  java.awt.Image.SCALE_SMOOTH ) ;
        jButton1.setIcon(new ImageIcon( newimg )); // NOI18N
        jButton1.setText("First");
        jButton1.setIconTextGap(0);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton_Next.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ImageIcon icon_next = new ImageIcon(path.concat("Resources/Images/next.png"));
        Image img_next = icon_next.getImage() ;
        Image new_img_next = img_next.getScaledInstance( 30, 20,  java.awt.Image.SCALE_SMOOTH ) ;
        jButton_Next.setIcon(new ImageIcon(new_img_next)); // NOI18N
        jButton_Next.setText("Next");
        jButton_Next.setIconTextGap(0);
        jButton_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NextActionPerformed(evt);
            }
        });

        jButton_Previous.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ImageIcon icon_previous = new ImageIcon(path.concat("Resources/Images/previous.png"));
        Image img_previous = icon_previous.getImage() ;
        Image new_img_previous= img_previous.getScaledInstance( 30, 20,  java.awt.Image.SCALE_SMOOTH ) ;
        jButton_Previous.setIcon(new ImageIcon(new_img_previous)); // NOI18N
        jButton_Previous.setText("Previous");
        jButton_Previous.setIconTextGap(0);
        jButton_Previous.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                ImageViewer.this.jButton_PreviousActionPerformed(evt);
            }
        });

        jButton_Last.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ImageIcon icon_last= new ImageIcon(path.concat("Resources/Images/last.png"));
        Image img_last = icon_last.getImage() ;
        Image new_img_last= img_last.getScaledInstance( 30, 20,  java.awt.Image.SCALE_SMOOTH ) ;
        jButton_Last.setIcon(new ImageIcon(new_img_last)); // NOI18N
        jButton_Last.setText("Last");
        jButton_Last.setIconTextGap(0);
        jButton_Last.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                ImageViewer.this.jButton_LastActionPerformed(evt);
            }
        });


        getContentPane().add(jLabel_Image);
        jLabel_Image.setBounds(100,1,400,400);
        jLabel_Image.setBackground(Color.black);

        getContentPane().add(button_box);
        button_box.setBounds(100,400, 400,30);
        button_box.add(jButton1);
        button_box.add(jButton_Previous);
        button_box.add(jButton_Next);
        button_box.add(jButton_Last);

        //pack();
    }

    // The First , Next , Previous ,Last Navigation Buttons

    // First
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {

        pos = 0;
        showImage(pos);

    }

    // Next
    private void jButton_NextActionPerformed(java.awt.event.ActionEvent evt) {
        pos = pos + 1;
        if(pos >= getImages().length)
        {
            pos  = getImages().length - 1;
        }
        showImage(pos);
    }

    // Previous
    private void jButton_PreviousActionPerformed(java.awt.event.ActionEvent evt) {
        pos = pos - 1;
        if(pos < 0)
        {
            pos = 0;
        }
        showImage(pos);
    }

    // Last
    private void jButton_LastActionPerformed(java.awt.event.ActionEvent evt) {
        pos = getImages().length - 1;
        showImage(pos);
    }

    private javax.swing.JLabel jLabel_Image;
    // End of variables declaration
}